name: janus
recipe: drupal8
config:
  php: '7.4'
  via: 'nginx'
  webroot: './web'
  database: 'mysql:5.7'
  composer_version: '2.0.7'
  xdebug: true
  config:
    php: lando.php.ini
services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt install libxslt1-dev -y
      - docker-php-ext-install xsl
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://janus.lndo.site"
  pma:
    type: phpmyadmin
